export const MARKET_CROPS = [
  // Fruits
  {
    name: 'Apple',
    segment: 'Fruit',
    season: 'Winter',
    category: 'fruits',
    price: '₹120–150/kg',
    details: 'Table apples for fresh consumption from hill regions.',
  },
  {
    name: 'Banana',
    segment: 'Fruit',
    season: 'All year',
    category: 'fruits',
    price: '₹26/kg',
    details: 'Cavendish bananas, ripened in controlled chambers.',
  },
  {
    name: 'Orange',
    segment: 'Fruit',
    season: 'Winter',
    category: 'fruits',
    price: '₹23/kg',
    details: 'Nagpur-type oranges, rich in juice and vitamin C.',
  },
  {
    name: 'Grapes',
    segment: 'Fruit',
    season: 'Summer',
    category: 'fruits',
    price: '₹45/kg',
    details: 'Green and black seeded/seedless table grapes.',
  },
  {
    name: 'Guava',
    segment: 'Fruit',
    season: 'Autumn',
    category: 'fruits',
    price: '₹17/kg',
    details: 'Medium-sized white-fleshed guava for table use.',
  },
  {
    name: 'Pomegranate',
    segment: 'Fruit',
    season: 'Winter',
    category: 'fruits',
    price: '₹120/kg',
    details: 'Bhagwa pomegranate, export-friendly grade.',
  },
  {
    name: 'Watermelon',
    segment: 'Fruit',
    season: 'Summer',
    category: 'fruits',
    price: '₹12/kg',
    details: 'Striped watermelon, high juice content.',
  },
  {
    name: 'Pineapple',
    segment: 'Fruit',
    season: 'All year',
    category: 'fruits',
    price: '₹28/kg',
    details: 'Kew and Queen varieties from coastal belts.',
  },
  {
    name: 'Papaya',
    segment: 'Fruit',
    season: 'All year',
    category: 'fruits',
    price: '₹17/kg',
    details: 'Table papaya, orange-fleshed, ready-to-ripe.',
  },
  {
    name: 'Sweet lime (Mousambi)',
    segment: 'Fruit',
    season: 'Winter',
    category: 'fruits',
    price: '₹29/kg',
    details: 'Juice-grade sweet lime with high brix.',
  },
  {
    name: 'Litchi',
    segment: 'Fruit',
    season: 'Summer',
    category: 'fruits',
    price: '₹150/kg',
    details: 'Seasonal litchi from eastern belts, fresh packed.',
  },
  {
    name: 'Strawberry',
    segment: 'Fruit',
    season: 'Winter',
    category: 'fruits',
    price: '₹700/kg',
    details: 'Table-grade strawberries for fresh or dessert use.',
  },
  {
    name: 'Tender coconut',
    segment: 'Fruit',
    season: 'All year',
    category: 'fruits',
    price: '₹29/piece',
    details: 'Tender drinking coconuts with soft malai.',
  },
  {
    name: 'Kiwi',
    segment: 'Fruit',
    season: 'Winter',
    category: 'fruits',
    price: '₹100–150/kg',
    details: 'Green kiwi suitable for retail packs and hotels.',
  },
  // Vegetables
  {
    name: 'Tomato',
    segment: 'Vegetable',
    season: 'All year',
    category: 'vegetables',
    price: '₹7–25/kg',
    details: 'Hybrid table tomato for fresh and processing use.',
  },
  {
    name: 'Potato',
    segment: 'Vegetable',
    season: 'All year',
    category: 'vegetables',
    price: '₹9–12/kg',
    details: 'Chipping / table potatoes from cold storage.',
  },
  {
    name: 'Onion',
    segment: 'Vegetable',
    season: 'All year',
    category: 'vegetables',
    price: '₹15–20/kg',
    details: 'Red onion, medium size, common mandi grade.',
  },
  {
    name: 'Cauliflower',
    segment: 'Vegetable',
    season: 'Winter',
    category: 'vegetables',
    price: '₹26/kg',
    details: 'Tight curd cauliflower, medium to large heads.',
  },
  {
    name: 'Cabbage',
    segment: 'Vegetable',
    season: 'Winter',
    category: 'vegetables',
    price: '₹8–20/kg',
    details: 'Green cabbage for fresh and coleslaw use.',
  },
  {
    name: 'Carrot',
    segment: 'Vegetable',
    season: 'Winter',
    category: 'vegetables',
    price: '₹48/kg',
    details: 'Red/orange carrot, suitable for table and juice.',
  },
  {
    name: 'Capsicum',
    segment: 'Vegetable',
    season: 'All year',
    category: 'vegetables',
    price: '₹78/kg',
    details: 'Green bell pepper, polyhouse grown.',
  },
  {
    name: 'Bhindi (okra)',
    segment: 'Vegetable',
    season: 'Monsoon',
    category: 'vegetables',
    price: '₹45/kg',
    details: 'Tender okra pods for fresh market.',
  },
  {
    name: 'Bottle gourd',
    segment: 'Vegetable',
    season: 'All year',
    category: 'vegetables',
    price: '₹11–12/kg',
    details: 'Long bottle gourd for sabzi and processing.',
  },
  {
    name: 'Green peas (fresh)',
    segment: 'Vegetable',
    season: 'Winter',
    category: 'vegetables',
    price: '₹60–100/kg',
    details: 'Shelled green peas, fresh harvest.',
  },
  {
    name: 'Drumstick',
    segment: 'Vegetable',
    season: 'All year',
    category: 'vegetables',
    price: '₹30–40/kg',
    details: 'Drumstick pods for fresh retail and hotels.',
  },
  {
    name: 'Broccoli',
    segment: 'Vegetable',
    season: 'Winter',
    category: 'vegetables',
    price: '₹100–150/kg',
    details: 'Export-grade broccoli crowns.',
  },
  // Cereals & grains
  {
    name: 'Wheat',
    segment: 'Cereal',
    season: 'Rabi',
    category: 'cereals',
    price: '₹25/kg',
    details: 'Milling grade wheat suitable for atta.',
  },
  {
    name: 'Rice',
    segment: 'Cereal',
    season: 'Kharif',
    category: 'cereals',
    price: '₹26/kg',
    details: 'Non-basmati parboiled/steam rice mix.',
  },
  {
    name: 'Maize',
    segment: 'Cereal',
    season: 'Kharif',
    category: 'cereals',
    price: '₹22/kg',
    details: 'Feed and grits grade maize.',
  },
  {
    name: 'Bajra (pearl millet)',
    segment: 'Cereal',
    season: 'Kharif',
    category: 'cereals',
    price: '₹26/kg',
    details: 'Pearl millet grain for flour and feed.',
  },
  {
    name: 'Jowar (sorghum)',
    segment: 'Cereal',
    season: 'Kharif',
    category: 'cereals',
    price: '₹33/kg',
    details: 'Food-grade sorghum grain.',
  },
  {
    name: 'Ragi (finger millet)',
    segment: 'Cereal',
    season: 'Kharif',
    category: 'cereals',
    price: '₹52/kg',
    details: 'Cleaned ragi grain for flour.',
  },
  {
    name: 'Brown rice',
    segment: 'Cereal',
    season: 'All year',
    category: 'cereals',
    price: '₹60/kg',
    details: 'Health-grade brown rice, semi-polished.',
  },
  {
    name: 'Broken wheat (dalia)',
    segment: 'Cereal',
    season: 'All year',
    category: 'cereals',
    price: '₹45/kg',
    details: 'Coarse broken wheat for porridge and daliya.',
  },
];

